version: '3.7'

services:
  events-web:
    container_name: '${CONTAINER_APP_NAME}'
    build: .
    image: eventsweb-site
    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: npm run start
    ports:
      - ${APP_EXPOSE_PORT}:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  storybook:
    build: .
    image: eventsweb-storybook
    container_name: '${CONTAINER_STORYBOOK_NAME}'
    command: npm run storybook
    ports:
      - ${STORYBOOK_EXPOSE_PORT}:6006
    volumes:
      - '.:/app'
      - '/app/node_modules'
    stdin_open: true
